### ISSUE TITLE
How to use this with `vue-filepond`?

### ISSUE THREAD

**Issue by fahmiegerton** [rahulhaque/laravel-filepond#1]
Hello, I tried to use your dependency, but seems not working and `$fileInfos` is just empty array. What does `Filepond::field($request->gallery)` does expect from `$request->gallery`? Because I need to know since `vue-filepond` didn't store anything on my `gallery` data object, so I manually inject the serverId when submitting the form like this

```
this.$refs.pond.getFiles().forEach((el) => {
      this.form.gallery.push(el.serverId);
});
```

Kindly need your help. Thank you !

**Comment by rahulhaque** [comment]
I believe you're following this approach mentioned here - [vue-filepond](https://github.com/pqina/vue-filepond). Make sure you set the value of `server` attribute of filepond component to your backend's filepond route defined in `config/filepond.php`. Now try uploading a file and see if filepond makes any xhr request in console. If you're getting any text response from the request which is encrypted of course, that means this library is working fine and you may have to tinker the frontend a bit. Can you follow the steps and post the response you're getting.
