### ISSUE TITLE
How can I get it for laravel 6?

### ISSUE THREAD

**Issue by takielias** [rahulhaque/laravel-filepond#11]
Can you please make a release for laravel 6?

**Comment by rahulhaque** [comment]
@takielias not anytime soon. If all the test cases pass right, I may release a 6.x-dev branch for testing asap. Current milestone is chunk upload. Hope you're enjoying the third party storage support recently added.

**Comment by takielias** [comment]
> @takielias not anytime soon. If all the test cases pass right, I may release a 6.x-dev branch for testing asap. Current milestone is chunk upload. Hope you're enjoying the third party storage support recently added.

Thanks for your support but My project was built on Laravel 6. That is why I can't use it. I may need to modify composer.json to check the update.

**Comment by rahulhaque** [comment]
@takielias try installing the package with `composer require rahulhaque/laravel-filepond:6.x-dev`

**Comment by takielias** [comment]
@rahulhaque That's awesome. I will check it. Thanks.

**Comment by takielias** [comment]
@rahulhaque Can you please make a compatible Laravel 6 version for [1.1.8](https://github.com/rahulhaque/laravel-filepond/tree/v1.4.8)? I badly need chunk support.

**Comment by rahulhaque** [comment]
@takielias uninstall the current version and install it again to have chunk upload. I won't be releasing any version for 6.x branch.

**Comment by takielias** [comment]
@rahulhaque Thanks a lot.
