### ISSUE TITLE
Attempt to read property "disk" on null"

### ISSUE THREAD

**Issue by aligulzar729** [rahulhaque/laravel-filepond#2]
Dear Sir
When I'm trying to move and validate or any other methods after field() it throws null errors.

```
Filepond::field($request->input('logo_url'))->validate(['logo_url' => 'required|image|max:3000']);
        $fileName = \Str::random(20) . '_brand';
        $destination = 'uploads/brand/';
$fileInfo = Filepond::field($request->input('logo_url'))
        ->moveTo($destination . $fileName);
```
Any help will be appreciated.

**Comment by rahulhaque** [comment]
Need more details. Please, provide the following.
1. Value of `$request->input('logo_url')`
2. Screenshot of the error or error file and line number.

**Comment by aligulzar729** [comment]
Fixed the previous one but now I'm facing this:
I want to move files to uploads/brand but this happens:
`copy(C:\\laragon\\www\\GulfinAPI\\public\\uploads/brand/1630473146_brand_YdFTaOv4DZfPSbXPsxuW.jpg): Failed to open stream: No such file or directory`

```
 // For single file validation
        Filepond::field($request->input('logo_url'))->validate(['avatar' => 'required|image|max:2000']);

        $fileName = time() . "_brand_" . \Str::random(20);
        $path = 'uploads/brand/';
        $fileInfo = Filepond::field($request->input('logo_url'))
            ->moveTo($path . $fileName);

        dd($fileInfo);
```

**Comment by aligulzar729** [comment]
And the value of $request->input('logo_url') is:
"eyJpdiI6IkV1R01BUEd6WFpnZCt5VVJHbFE3c3c9PSIsInZhbHVlIjoiVGhDVytES3hrcmFQd0tyZnRILzB2YUprNVNNSzgzM0t0VXp1bHVmWGZNST0iLCJtYWMiOiI0NzU1ZDU4NDYwMTY3MTNhZmRhZjlhYmZhZDgwNDkxMjcwYWRmMTJiYWM5ZTMzMjQyNDE4NDg2Yjg0N2M4MTE0In0="

**Comment by rahulhaque** [comment]
The folder you're trying to move your files to doesn't exist. Create the folder and make sure you're directing to the correct path.

**Comment by aligulzar729** [comment]
> The folder you're trying to move your files to doesn't exist. Create the folder and make sure you're directing to the correct path.

![image](https://user-images.githubusercontent.com/32263497/131628838-2fff3a93-d92d-490f-9b1d-858b3886d507.png)

It exists

**Comment by rahulhaque** [comment]
This is not a package issue. Read more about folder and directory access in laravel. Use `public_path` helper described [here](https://laravel.com/docs/8.x/helpers#method-public-path).

**Comment by aligulzar729** [comment]
Sorry. But thanks BTW.
