### ISSUE TITLE
The file "..." does not exist

### ISSUE THREAD

**Issue by MrMooky** [rahulhaque/laravel-filepond#23]
When using S3 as temp disk and permanent storage, I get the following error when storing the file:

`The file "filepond/temp/YTXkkiSEtz6IEZNT4nKTNSvRHkX9nHIq4l4jbEYS.zip" does not exist`

Is this a known issue? S3 being AWS here. When using this locally, eg. with a local storage, the error is not thrown.

**Comment by MrMooky** [comment]
Ah, just found this:

> This method is not available when third party storage is set as your temporary storage. The files are uploaded directly to your third party storage and not available locally for any further modification. Calling this method in such condition will throw error that the file is not found.

**Comment by rahulhaque** [comment]
@MrMooky finally someone who has read the docs 👏🏻 Most of the past issues were me explaining what’s in the docs.
