### ISSUE TITLE
Problema no getFile()

### ISSUE THREAD

**Issue by 1JP** [rahulhaque/laravel-filepond#25]
Estou utilizando a função getFile() para pegar as informações das fotos, mas não esta vindo as informações mesmo com dados na função Filepond::field(). Pode me ajudar nisso.
![image](https://user-images.githubusercontent.com/31634902/187253823-5c84e533-3886-454a-bd55-becb8044d5fb.png)

**Comment by rahulhaque** [comment]
@1JP closing as duplicate.
