### ISSUE TITLE
How to access the data?

### ISSUE THREAD

**Issue by xfkrahmad** [rahulhaque/laravel-filepond#28]
![Screenshot_116](https://user-images.githubusercontent.com/71373710/204078745-e55c0c78-b57f-4584-bff6-34fd16081b28.png)
I using a spatie media, so i need a string of the image path. for now i just do like on the screenshot, and i believe this is incorrect ways.
thank for your response

**Comment by rahulhaque** [comment]
@xfkrahmad use the `getFile()` method to get the file object to work with. With Spatie's media library package, it is as easy as -
```php
// Single file
$product->addMedia(Filepond::field($request->image)->getFile())->usingName('...')->toMediaCollection('...');

// Multiple files
$images = Filepond::field($request->images)->getFile();
foreach ($images as $image) {
    $product->addMedia($image)->usingName('...')->toMediaCollection('...');
}
```

**Comment by xfkrahmad** [comment]
> @xfkrahmad use the `getFile()` method to get the file object to work with. With Spatie's media library package, it is as easy as -
> 
> ```
> // Single file
> $product->addMedia(Filepond::field($request->image)->getFile())->usingName('...')->toMediaCollection('...');
> 
> // Multiple files
> $images = Filepond::field($request->images)->getFile();
> foreach ($images as $image) {
>     $product->addMedia($image)->usingName('...')->toMediaCollection('...');
> }
> ```

thank you. it solved
