### ISSUE TITLE
Error when using onprocessfile - not valid JSON returned.

### ISSUE THREAD

**Issue by rstanislav** [rahulhaque/laravel-filepond#38]
Hello! When files uploaded response contains some long string, not JSON, i have added filepond* to except array, tried to disable debugbar, but nothing changed..
In dev console:
caught SyntaxError: Unexpected token 'e', "eyJpdiI6In"... is not valid JSON
 
request to filepond during upload returns string:
eyJpdiI6InQ1b3hTb2RBVVZGNWdybDRIeC9icGc9PSIsInZhbHVlIjoib1d5RVRNRDFnVzRLNzE2RzRwVklMbGs5eUFnUC96YWJoc2ZxaDRBR0QrVT0iLCJtYWMiOiIyMjAzZTA2NjU5OWMwMjdjMTQzZmRiMzY2ZTBiYWRlMmM1NDRjMzFiNTc3NGQxMGNmMWVhMWE5M2MzYTgxZDgzIiwidGFnIjoiIn0=

edit: Looks like return string is always the same, no matter what file i upload.

Project: Laravel 10 + Livewire, php 8.1

Help me please :(

**Comment by rstanislav** [comment]
I think i found reason - server returns encrypted id of file (Crypt::encrypt(['id' => $filepond->id])), but i dont understand how this function from example should work:
const handleFilePondAvatarProcess = (error, file) => {
    form.avatar = file.serverId;
};

My code:
```
filePond = FilePond.create(filePondElement, {
                            allowMultiple: true,
                            instantUpload: true,
                            credits: false,
                            // chunkUploads: true,
                            // chunkForce: true,
                            acceptedFileTypes: ['image/*', 'application/pdf'],
                            server: {
                                url: '/filepond',
                                headers: {
                                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                                }
                            },
                            onprocessfile: (error, file) => {
                                if (!error) {
                                    const response = JSON.parse(file.serverId);
                                    console.log(file.serverId);
                                }
                            },
                        });
```
Or i got it wrong and "on" event and onprocessfile is different events ?

**Comment by rahulhaque** [comment]
I think you've a unique case here. Why don't you add the encrypted string to array without `JSON.parse()`. Then submit and process the files in the server.

**Comment by rstanislav** [comment]
Found another way: in sweetalert2 submit function i call filePond.getFiles().map(x => x.serverId) to get array of serverid's, looks like this is only way, because processfile returns serverid, but removefile does not return serverid (author of filepond removed it some time ago, and didnt fixed it.. )

Thanks for help and this great laravel package !
