### ISSUE TITLE
Allow use of custom model

### ISSUE THREAD

**Issue by henryavila** [rahulhaque/laravel-filepond#45]
In some cases we need to use a custom model. In my case, I have a multi tentant app, So I need do save more data in the Filepond model.

I've created the PR #44, if you could accept this PR, I will be so greatfull

**Comment by rahulhaque** [comment]
Hi @henryavila, welcome here. Would you kindly explain, exactly what type of scenario forced you to use a custom model for filepond? I'm trying to have a deeper understanding of the issue you're facing. As a multi-tenant app developer myself, I never needed custom filepond model. So I need to be fully sure before I merge the changes.

**Comment by henryavila** [comment]
Hi @rahulhaque, In use multi tenant with a single database. One database for `landlord` and other for `tenants`
So every tenant model must have the tenant FK. Beoynd that, every model hust have some custom connection config. So every model (Landlord or Tenant) contains one Trait that encapsulate Landlord or Tenant connection logic.

My custom model is like this:
```php
class Filepond extends \RahulHaque\Filepond\Models\Filepond
{
    use ModelWithTenant;
}
```

**Comment by rahulhaque** [comment]
@henryavila filepond model is independent of any tenant dependency, meaning, the model's soul purpose is to give filepond a storage base for managing its temporary uploaded files. This model is just a helper. Those temporary files have unique ids and have no meaning to you or your application unless moved to permanent storage. You can keep using the filepond model globally for all tenants. However to manage tenant specific relation and files, you can make a model named `UploadedFile` or something like that. Update the model when you move the files to permanent storage.

I am open to hear from you if the above pattern doesn't fix your issue.

**Comment by rahulhaque** [comment]
@henryavila waiting for your response.

**Comment by henryavila** [comment]
HI @rahulhaque, sorry for late response.

That's my user casa where the Temporary files, and the model, is relevant to my application:
The forms where the end user will send files is from a public page, so there's no authenticated user sending the form.
Every tenant has their own website, (the app runs on a proxy site).

If a lot o temporary files are not finished (moved to S3), this means that we probally have some UX problem with that tenant (The user case may differ from tentant to tenant. In this situation, probally, the end user are not using correctly the form. The common reason is that he don't understand how to use the form. Yes, we have all kind of users, from tenanges to great-grandfathers).

So my idea to keep the `Filepond` model on Tentant database to keep a track on this possible failed use of the forms.
To keep this data on Tenant Model, a `Trait` is the way. I can extend the controller and change your logic, but It can break the app in futures updates, when you update the package, so I don't believe extending the controller is a good aproach.


I can move the filetonds table to landlord database and create a observer and save the `tenant_id` on `Filepond` model and make my analyse on prune command. But this solution has some problems:
1. Duplicate some code
2. Have tenant data on landlord database

That's why I avoided this approach.

If you could allow to configure the database connection to `Filepond` model we don't  need to overwrite the model. I still have to duplicate some code, but at least, the table will stay in the correct database.

**Comment by rahulhaque** [comment]
@henryavila thanks for the explanation. I am processing this in my head. The reason I have omitted allowing extension of `Filepond` model is that you cannot change the internal logic for writing any data to it. You can edit the migration file to add extra columns and to write to these columns, I have added [getModel()](https://github.com/rahulhaque/laravel-filepond#getmodel) method to get the inner model. I don't think this will solve your use case where different model needs different database connections.

> If you could allow to configure the database connection to Filepond model we don't need to overwrite the model. I still have to duplicate some code, but at least, the table will stay in the correct database.

So the main issue you're facing with multi-tenancy is the database connection for each model as it can be dynamic, am I right? Please correct me if I am wrong. If this is the case, it would be enough for you, if I let you either **extend the model** or **set connection on the model**, right?

I've seen your pull request. Not trying to be rude here, it's a little messy. You even changed the style of my service class. Do you really need interface for extending the model? Your custom model can extend `Filepond` model. I would simply allow changing the model from the `config` file without all these extra changes, depends on your answer.

Please, take your time to read this and answer. Sorry for being this cautious. As a package maintainer I have to be really sure before making any changes. Hope you'll understand. Let's make this discussion fruitful.

**Comment by rahulhaque** [comment]
@henryavila thanks for the reply.

> If I can extend the model and your code alwyas use my model, and not the base model, it's correct. That's exactly what I try to achieve with the PR.

Yes, this is what I meant. I'll let you set a `custom` model through `config` file. That `custom` model should extend `filepond` model to avoid any type checking. The whole package will use your set `custom` model for everything. No need for interface. This way both of our model logic will stay as is. I don't have any issues with remaining changes. Just try to keep the coding style the same as much as possible. I may push new commit to fix things in your branch.

If the above idea fits your need, I'll update the dev branch for you to further testing. Is that okay?

**Comment by henryavila** [comment]
It's perfect for me @rahulhaque. Thanks

**Comment by rahulhaque** [comment]
Hi @henryavila. I have updated the dev branch. Can you please test and confirm if this is working for you. If it does, I'll go for a release. Install with `composer require rahulhaque/laravel-filepond:dev-dev`

**Comment by henryavila** [comment]
Hi @rahulhaque. I will be albe to test it tomorrow.

No problem in implemting it by youself. The code become more clear.

As I can see, 2 parts of your package will not work with custom model:


`src/Traits/HasFilepond.php` became useless with custom model, since it will get the wrong model.
`src/Console/FilepondClear.php`  will not work with custom model, and anyone that need custon model will have to implement the command.

Any chance to you ad custom model to `Trait` and `Console Command` ?

**Comment by rahulhaque** [comment]
@henryavila I missed updating the `src/Console/FilepondClear.php`  flie. I've pushed the changes to dev so that you get the latest version tomorrow. Hope to hear from you soon.

**Comment by henryavila** [comment]
Hi @rahulhaque, I tested and it's working perfect. Thanks!

**Comment by rahulhaque** [comment]
Hello @henryavila, thank you for the feedback. I'll release a new version tomorrow.

**Comment by rahulhaque** [comment]
Hello @henryavila, I've just released a new version. Please, update. Also, thanks a lot for your valuable time and effort to discuss, suggest and provide feedback where necessary for this update. I really appreciate that. Thanks again.
