### ISSUE TITLE
Error at nested validation

### ISSUE THREAD

**Issue by Redleks** [rahulhaque/laravel-filepond#46]
Hello.

In case at nested validation rules like:

```php
public function rules()
{
  return [
   'variants.*.image' => Rule::filepond([
                'image',
                'mimes:jpeg,jpg,png',
                'max:8000',
            ]),
  ];
}
```

I had error

> Argument #1 ($data) must be of type string, array given, called in /var/www/html/vendor/rahulhaque/laravel-filepond/src/AbstractFilepond.php on line 52

At AbstractFilepond.php on line 52 in debug mode i see:
![Xnip2023-10-08_19-25-22](https://github.com/rahulhaque/laravel-filepond/assets/6208668/c9267477-262b-40d9-8656-2125d7d4f186)

Its bug or i do something wrong?

**Comment by rahulhaque** [comment]
Hi @Redleks, please share the code for your filepond input and some context. Why is filepond image inside a nested array? Are you using multiple filepond instance? Are you using any plugins for filepond?  I need to reproduce the issue.

**Comment by Redleks** [comment]
I have two models with relations
- Product (HasMany ProductVariant)
- ProductVariant (BelongsTo Product)

I have complicated form which in one request create Product and attach multiple ProductVariants to it.

ProductVariants passed in array like:

```json
{
  "name": "name",
  "slug": "",
  "visible": true,
  "featured": false,
  "annotation": "",
  "description": "",
  "meta_title": "",
  "meta_description": "",
  "votes": 0,
  "rating": 0,
  "brand_id": null,
  "brand": null,
  "categories": [],
  "variants": [
    {
      "name": "name1",
      "sku": "1",
      "price": 0,
      "price_old": "",
      "units": "unit",
      "amount": "",
      "image": "eyJpdiI6IkJ0REpaK1Ezcm5MeGo3TTZsYmNpTkE9PSIsInZhbHVlIjoiOHBzQkd3QWhxWDJwZEhYYzd4d1h4TUphV1lUbkVhY3hIYUd3S2NnMEtpRT0iLCJtYWMiOiI4M2RiZGUzYmE1MzJiZWIxYzMzOGYxZjcwMzQ5N2Y5ODVkNjNlZjA4OWFkY2EzNTMyNjcxODI4Mjg3NWNiN2JmIiwidGFnIjoiIn0="
    },
    {
      "name": "name2",
      "sku": "2",
      "price": 0,
      "price_old": "",
      "units": "unit",
      "amount": "",
      "image": "eyJpdiI6Imd5VHhxS1hMdEgwbFJGWFZlekFVNVE9PSIsInZhbHVlIjoidWRsSzI4Q05ldldVYitIR1cxQnJ2S1czUDZPeEM2R2JLUmpBU282V2xPdz0iLCJtYWMiOiI3ODA0N2Q1MWYyODY3MzM1ZjdkMjNiNWYxMTY2YTYyMjFlMmYxYWUyYmVjNDE3OTZhYzNkYTY1MWEzNGE1N2FlIiwidGFnIjoiIn0="
    }
  ],
  "categories_ids": []
}
```

ProductRequest:

```php
class ProductRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'name' => 'required|string|max:255',
            'slug' => 'string|max:255|nullable',
            'annotation' => 'string|max:255|nullable',
            'description' => 'string|max:255|nullable',
            'visible' => 'boolean|nullable',
            'featured' => 'boolean|nullable',
            'brand_id' => 'integer|nullable',
            'votes' => 'integer',
            'rating' => 'numeric',
            'images.*' => Rule::filepond([
                'image',
                'mimes:jpeg,jpg,png',
                'max:8000'
            ]),
            'categories_ids' => 'present|array',
            'categories_ids.*' => 'integer|exists:categories,id',
            'variants' => 'required|array|min:1',
            'variants.*.name' => 'required|string|max:255',
            'variants.*.sku' => 'string|max:255|nullable',
            'variants.*.price' => 'numeric',
            'variants.*.price_old' => 'numeric|nullable',
            'variants.*.units' => 'string',
            'variants.*.amount' => 'numeric|nullable',
            'variants.*.image' => Rule::filepond([
                'image',
                'mimes:jpeg,jpg,png',
                'max:8000',
            ]),
        ];
    }
}
```

ProductController (dummy code)
```php
public function store(ProductRequest $request)
    {
        $validated = $request->validated();

        $product = Product::create($validated);
        
        $product->categories()->attach($validated['categories_ids']);
        
        if ($request->images) {
            foreach ($request->images as $item) {
                $product->addMedia(Filepond::field($item)->getFile())->toMediaCollection(
                    Product::MEDIA_COLLECTION_NAME
                );
            }
        }

        foreach ($validated['variants'] as $variant) {
            $variantWithProduct = array_merge($variant, ['product_id' => $product->id]);

            $productVariant = ProductVariant::create($variantWithProduct);

            if (isset($variant['image'])) {
                $productVariant
                    ->addMedia(Filepond::field($variant['image'])->getFile())
                    ->toMediaCollection(ProductVariant::MEDIA_COLLECTION_NAME);
            }
        }

        session()->flash('status', __("app.created"));

        return redirect()->route('admin.product.edit', $product->id);
    }
```

**Comment by rahulhaque** [comment]
@Redleks thank you. I'll have a look.

**Comment by rahulhaque** [comment]
@Redleks can you please test the fix by upgrading package with `composer require rahulhaque/laravel-filepond:dev-dev`? I'll release a new version when done.

**Comment by Redleks** [comment]
@rahulhaque now bug is fixed, but there's validation error: **The variants.0.image field must be an image.** Image pasted by string: "image": "eyJpdiI6Imd5VHhxS1hMdEgwbF....". And request the same as I described earlier 

I'll test some more and report back a little later. Thanks for that!

**Comment by rahulhaque** [comment]
@Redleks I am also having a look into this. There's complexity in processing multiple filepond files.

**Comment by Redleks** [comment]
Unfortunately validation is broken everywhere in the arrays. I saw you commit and test. You use $response->content() (base64 maybe) and multipart/form-data:

```php
$responses[] = [
                'title' => fake()->name(),
                'image' => $response->content(),
            ];
```

But iam using inertia js and send json with filepond serverid, not multipart/form-data.

**Comment by rahulhaque** [comment]
Yes and it's okay. I'll have a through check. You can revert back to original version for now.

**Comment by Redleks** [comment]
@rahulhaque I did a little research and make some fix. Look pls:


```php
public function passes($attribute, $value)
    {
        $file = Filepond::field($value)->getFile();

        data_set($this->data, $attribute, $file);

        $validator = Validator::make(
            $this->data,
            [$attribute => $this->rules],
            $this->validator->customMessages,
            $this->validator->customAttributes
        );

        $this->messages = $validator->errors()->all();

        return ! $validator->fails();
    }
```

**Comment by Redleks** [comment]
The problem was that your previous fix created a new object in the data array with a key like 'variant.0.image', ($data['variant.0.image']) but the validator looks in the original array in the place of $data['variants'][0]['image']

**Comment by rahulhaque** [comment]
@Redleks you're absolutely right. I've just pushed some changes to dev. If you want you can make a pull request as well. Please test the new changes.

**Comment by Redleks** [comment]
Everything seems to be working fine! 
I think I'm not doing a pull request. I'd rather test it more today, and let you know if I find anything.

Waiting for the release! :)

**Comment by rahulhaque** [comment]
@Redleks you don't know how hard I was searching for this helper function but couldn't put in words to google, lol.  Dev thing I guess. Thanks a lot for this. I've just released a new version. Thank you for using my package. Have a great day.

**Comment by rahulhaque** [comment]
@Redleks Closing this issue for now. If any issue arises, please do a mention. Thanks for the clear explanation and suggesting a solution. I really appreciate that. Take care.
