### ISSUE TITLE
Use of union types causes a breaking change

### ISSUE THREAD

**Issue by Pheasey** [rahulhaque/laravel-filepond#49]
Changes made in https://github.com/rahulhaque/laravel-filepond/commit/fb9891644b689a6c85e2b1a676845e29d3e7d904 add [union types](https://php.watch/versions/8.0/union-types) to several method arguments so the project no longer works with PHP 7.3.

This is still an option defined in the [composer.json](https://github.com/rahulhaque/laravel-filepond/blob/master/composer.json#L20) so should be amended or reverted depending on the desired supported versions.

**Comment by rahulhaque** [comment]
Hi @Pheasey, thanks for the report. You're using it in Laravel 7 project right? I am thinking about updating the minimal PHP version to 7.4. Will that be okay with you?

**Comment by Pheasey** [comment]
@rahulhaque Union types are a PHP 8 feature, this can be seen in the [change log](https://www.php.net/manual/en/language.types.declarations.php) so you would need to drop 7.4 support too.

**Comment by rahulhaque** [comment]
@Pheasey I've moved to the major versioning aligned with major Laravel release. Please, do report if you find anything unusual. Thank you for this.
