### ISSUE TITLE
Remove file(s) after Upload.

### ISSUE THREAD

**Issue by time-to-dev** [rahulhaque/laravel-filepond#51]
Hello everyone,

I have encountered the following situation: 

### Situation
as soon as I upload file(s) and then delete a file (via Filepond UI) and then save my form, I get the following error:

`
RahulHaque\Filepond\AbstractFilepond::createFileObject(): Argument #1 ($filepond) must be of type RahulHaque\Filepond\Models\Filepond, null given, called in /home/vagrant/projects/***/vendor/rahulhaque/laravel-filepond/src/Filepond.php on line 43
`

#### Server side
- Package Version: 10.0.0
- PHP Version: 8.2.9
- Laravel Version: 10.35.0

Possibly relevant: I use the Jetstream/Inertia/Vuejs stack.

The `filepond.php` settings that deviate from the default file:
```
'middleware' => [
    'web', 'auth', 'authorize_by_route',
],
'soft_delete' => true,
```

Middleware for store route:
```
    public function rules(): array
    {
        return [
            ...
            'attachments' => 'required|array',
            'attachments.*' => [
                'required',
                Rule::filepond([
                    'max:10240',
                    'mimes:jpeg,png,pdf',
                ]),
            ],
        ];
    }
```

#### NPM Packages
```
    "devDependencies": {
        "vite": "^4.0.0",
        "vue": "^3.3.6",
        ...
    },
    "dependencies": {
        "filepond": "^4.30.4",
        "filepond-plugin-file-validate-type": "^1.2.8",
        "filepond-plugin-image-preview": "^4.6.11",
        "vue-filepond": "^7.0.3",
        ...
    }
```

#### Frontend (Vuejs Component)
```vue
<FilePond
    name="attachment"
    ref="filepond"
    :label-idle="$t('layouts.appLayout.filepondLabelIdle')"
    accepted-file-types="image/jpeg, image/png, application/pdf"
    v-bind:files="form.attachments"
    v-bind:allow-multiple="true"
    v-on:init="handleFilePondInit"
    v-on:processfile="handleFilePondProcessFile"
    v-on:removefile="handleFilePondRemoveFile"
    v-bind:server="{
        process: $page.props.filepondServerUrl,
        revert: $page.props.filepondServerUrl,
        headers: {
            'X-CSRF-TOKEN': $page.props.csrfToken,
        },
    }"
    credits="false"
    aria-describedby="helper-text-filepond"
/>
```

Can you reproduce the error?
I am willing to provide further information if necessary.

Thank you very much for the work you have done and for providing this package!

**Comment by time-to-dev** [comment]
I don't know if this is the right approach to fix the bug(!?), I haven't familiarised myself enough with the code yet, but it could be the solution:

`vendor/rahulhaque/laravel-filepond/src/Rules/FilepondRule.php`
```
class FilepondRule implements DataAwareRule, Rule, ValidatorAwareRule
{
    public function passes($attribute, $value)
    {
        $file = Filepond::field($value)->getFile();

        // Start possibly a bugfix
        if ($file !== null) {
            data_set($this->data, $attribute, $file);
        } else {
            data_forget($this->data, $attribute);
        }
        // End possibly a bugfix

        $validator = Validator::make(
            $this->data,
            [$attribute => $this->rules],
            $this->validator->customMessages,
            $this->validator->customAttributes
        );

        $this->messages = $validator->errors()->all();

        return ! $validator->fails();
    }
}
```

`vendor/rahulhaque/laravel-filepond/src/Filepond.php`
```
class Filepond extends AbstractFilepond
{
    public function getFile()
    {
        if (! $this->getFieldValue()) {
            return null;
        }

        if ($this->getIsMultipleUpload()) {
            return $this->getFieldModel()->map(function ($filepond) {
                return $this->createFileObject($filepond);
            })->toArray();
        }

        // Start possibly a bugfix
        if (! $this->getFieldModel()) {
            return null;
        }
        // End possibly a bugfix

        return $this->createFileObject($this->getFieldModel());
    }
}
```

**Comment by rahulhaque** [comment]
Hi @time-to-dev, can you please elaborate this -
> as soon as I upload file(s) and then delete a file (via Filepond UI) and then save my form, I get the following error:
Why would you delete the file from filepond before submitting the form?

**Comment by time-to-dev** [comment]
Hi @rahulhaque, what I mean by deleting the files from Filepond, is the handling of filepond's [revert](https://pqina.nl/filepond/docs/api/server/#revert) process/endpoint.
In our case, this is the route 'filepond-revert' from the `vendor/rahulhaque/laravel-filepond/routes/web.php` file that is used.

For example, if the user has selected the wrong file and wants to delete it from the selection, they can do this by tapping the "Undo" button. Completely normal procedure. Nothing special. This functionality is also included in your linked example.

I am expanding my Vuejs code snippet (simplified, all other fields and functions removed):

#### Vuejs Component
```
<template>
    <AppLayout title="Filepond">
        <div class="py-12">
            <form @submit.prevent="submitForm">
                <FilePond
                    name="attachment"
                    ref="filepond"
                    :label-idle="$t('layouts.appLayout.filepondLabelIdle')"
                    accepted-file-types="image/jpeg, image/png, application/pdf"
                    v-bind:files="form.attachments"
                    v-bind:allow-multiple="true"
                    v-on:init="handleFilePondInit"
                    v-on:processfile="handleFilePondProcessFile"
                    v-on:removefile="handleFilePondRemoveFile"
                    v-bind:server="{
                        process: $page.props.filepondServerUrl,
                        revert: $page.props.filepondServerUrl,
                        headers: {
                            'X-CSRF-TOKEN': $page.props.csrfToken,
                        },
                    }"
                    credits="false"
                    aria-describedby="helper-text-filepond"
                />
                <button type="submit" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center ...">
                    Save
                </button>
            </form>
        </div>
    </AppLayout>
</template>

<script>
import AppLayout from '@/Layouts/AppLayout.vue';
import { Link } from '@inertiajs/vue3';
import {useForm} from 'laravel-precognition-vue-inertia';
import vueFilePond from 'vue-filepond';
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';

// Create component
const FilePond = vueFilePond(
    FilePondPluginFileValidateType,
    FilePondPluginImagePreview
);

export default {
    components: {
        AppLayout,
        Link,
        FilePond,
    },
    data() {
        return {
            form: useForm('post', route('news.store'), {
                attachments: [],
            }),
        };
    },
    methods: {
        async submitForm() {
            await this.form.submit();
        },
        handleFilePondInit() {
            console.log("FilePond has initialized.");
        },
        handleFilePondProcessFile(error, file) {
            // Add uploaded file to data source.
            this.form.attachments.push(file.serverId);
        },
        handleFilePondRemoveFile(error, file) {
            // Remove the deleted file from the data source.
            const index = this.form.attachments.findIndex(f => f.id === file.id);
            if (index !== -1) {
                this.form.attachments.splice(index, 1);
            }
        },
    },
};
</script>
```

#### Reproducible through steps
1) load the page.
2) select two images by clicking on Filepond area.
3) delete one of the two images by tapping the undo button.
4) click on the Save button to submit the form data.

#### Request Body
```
{
    "attachments": [
        "eyJpdiI6Ikxmcy9tVnpwOEhLRkhaRFpaM0tkVlE9PSIsInZhbHVlIjoiRkp2eUVIWkpUQkFyT290b1J4SU50T0RhN3FudlBRNXZTMmRIRzk0Y3U5Yz0iLCJtYWMiOiJlNTI5NzFlNzc3MTA1MTllZmFhZjMyYzZiMjg3NWUzNDQzOTIyMGIxZDk4Njk2ZmM4NmFhNzgwYmRlZWQ5MWVhIiwidGFnIjoiIn0=",
        "eyJpdiI6ImlKTkpiSEM3d1k3QWQxZSt4Tm56WEE9PSIsInZhbHVlIjoiVzYwTTQwMURyazU0bXFXbEpMbFNxV1BiN0RBb05GbFIzSjRJWjlMTHlRST0iLCJtYWMiOiIwOWNlYWMzZGE0ZWE2MTRhOTdjNGEzZmM1NDE4NTY0ZGU4MDUzZWNhMzY4ZDY3MjY1NGY2NDgyODBhZWFhYWUzIiwidGFnIjoiIn0="
    ]
}
```

#### Response/Result
As a result, I get the error described above.

Obviously, I have made a mistake and have an error in the handleFilePondRemoveFile() function. This means that the `serverId` is not deleted from `attachments` array.
I only realised this after creating this issue.
The server receives two IDs, although one of them no longer exists and can be found, which then leads to a 500 error in the following file:
`/vendor/rahulhaque/laravel-filepond/src/Filepond.php`

**However, I think no matter how well or badly the frontend works or how the requests are structured, the backend must not break just because a not quite correct request was made.** 

_My English is not good enough and I have to rely on a translator. I apologise if the sentence structure is poor._

**Comment by rahulhaque** [comment]
@time-to-dev thank you for the detail explanation. Kudos to you for finding out the issue by yourself. You english seems fine too. And about the issue -
> However, I think no matter how well or badly the frontend works or how the requests are structured, the backend must not break just because a not quite correct request was made.

Filepond has its own set of rules for handling files from frontend. It expects the backend to be aligned with those set of rules. If I just ignore the fact when someone didn't implement filepond correctly in the frontend and don't throw any error, frontend dev will never realize there's something wrong with his implementation.

You wouldn't have opened this issue and learn that you haven't implemented `handleFilePondRemoveFile()` method wrong if I didn't throw any error at first place. This saves you in long run. Thank you for your suggestion and using my package.
