### ISSUE TITLE
links to laravel versions are broken

### ISSUE THREAD

**Issue by stratboy** [rahulhaque/laravel-filepond#55]
Hi, I links to laravel versions like this:

https://github.com/rahulhaque/laravel-filepond/tree/10.x

are broken, because they all show the same home page

**Comment by rahulhaque** [comment]
@stratboy I've updated the links for easier navigation.

**Comment by stratboy** [comment]
> @stratboy I've updated the links for easier navigation.

Thnk you very much!!

**Comment by rahulhaque** [comment]
@stratboy thanks a lot for the donation 🙏 It means a lot to me. ❤️

**Comment by stratboy** [comment]
To say the truth, It's very low, sorry, you deserve a lot more, but I'll do as soon as I'll use you code for some commercial project (I hope). Right now I'm only studying Laravel and trying to (re)make a no profit app for seed-savers I developed several years ago, when I had the idea and made the design and frontend programming, while a friend of mine did the backend with Rails. Now I'm trying to rebuild it with Laravel and some new stuff,  just to learn (http://www.cercasemi.it).

Then I hope to get some real job for web applications. Until now I've been coding (almost) only 100% custom wordpress themes/websites and js apps.

**Comment by rahulhaque** [comment]
@stratboy thanks again for the support no matter how big or small it is. Wishing you all the very best in all your future endeavors. Have a great day.

**Comment by stratboy** [comment]
Thank you! You too!
