### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by Nezimed** [rahulhaque/laravel-filepond#57]
Will this package support laravel 11?

**Comment by rahulhaque** [comment]
@Nezimed will release 11.x version soon.

**Comment by OzanKurt** [comment]
Thanks!

**Comment by rahulhaque** [comment]
@Nezimed @OzanKurt added laravel 11 support. Please close the issue after testing.

**Comment by Nezimed** [comment]
No issues after updating. Thanks
