### ISSUE TITLE
Delete fails with multiple upload

### ISSUE THREAD

**Issue by horo42** [rahulhaque/laravel-filepond#6]
When uploading multiple files with filepond, and then calling
`$filepond = Filepond::field($filepondToken)->delete();`
The error is: Method Illuminate\Database\Eloquent\Collection::delete does not exist.

The reason is that at
https://github.com/rahulhaque/laravel-filepond/blob/886ac39dfa2ccba9a39acd5908f540eee4131995/src/Filepond.php#L153-L171

there is a missing else case, since `$filepond = $this->getFieldModel();` returns a Collection, it tries calling ->delete() on a Collection instance.

**Comment by rahulhaque** [comment]
@horo42 I feel like I missed a simple return to break the condition. Thanks for identifying the issue. Just released a new version for Laravel 8 channel. Please check.

**Comment by horo42** [comment]
Thanks for the quick reply and fix, I found no issues with the new version. 👍
