### ISSUE TITLE
Uploading large files and using `moveTo()` can produce out of memory exceptions

### ISSUE THREAD

**Issue by anselmpaul** [rahulhaque/laravel-filepond#60]
Hey,

we've been using this package to manage uploads of rather large files (movies, up to 10GB) and have repeatedly run into out-of-memory exceptions. I think I've been able to track it down to the `moveTo()` function, which calls `putFile()` which runs:
https://github.com/rahulhaque/laravel-filepond/blob/a3bfa1bc2a27d0fd9f936f072275ae7bbb3c93af/src/Filepond.php#L185 

I think replacing the `Filesystem::get()` to read the contents of the file with `Filesystem::readStream()` could fix this issue.

**Comment by rahulhaque** [comment]
@anselmpaul thanks for opening the issue and suggesting possible fix. I'll have a look and get back to you as soon as possible.

**Comment by rahulhaque** [comment]
@anselmpaul which version you're using?

**Comment by anselmpaul** [comment]
@rahulhaque We are using v10. I've just tried out the dev version and it seems to be working! Thank you for the fast response :)

**Comment by anselmpaul** [comment]
Seems to work after some testing so I'll close this.
