### ISSUE TITLE
Attempt to read property "extension" on null

### ISSUE THREAD

**Issue by clickanidea** [rahulhaque/laravel-filepond#8]
I randomly get the error, using always the same image for testing
I need the extension because I am changing the file name on store
Database record is stored correctly ...

<img width="279" alt="Screenshot 2021-11-11 at 16 26 42" src="https://user-images.githubusercontent.com/70272902/141315290-c018e866-1f76-4c97-8110-9059100c0590.png">

```php
$logoType = Filepond::field($request->logo);
$logoType = $logoType->getModel()->extension;
```

**Comment by rahulhaque** [comment]
```php
Filepond::field($request->logo)->getFile()->extension()
```
It's all in the documentation - [getFile()](https://github.com/rahulhaque/laravel-filepond#getfile)

**Comment by rahulhaque** [comment]
@clickanidea To store the file, use the `copyTo()` or `moveTo()` method. You don't need to pass file extension for storing. Even if you need the extension, get that with -
```php
Filepond::field($request->logo)->getFile()->extension()
```

**Comment by clickanidea** [comment]
This is what i am doing : 
```php
$logoType = Filepond::field($request->logo)->getFile()->extension();
$logoName = 'logo-' . now()->timestamp . '.' . $logoType;
$fileInfo = Filepond::field($request->logo)
            ->moveTo('storage/' . $logoName);
```
If i change the name without the extension the file is stored without, so it's not renderable.
