### ISSUE TITLE
Does not work on AWS S3/wasabi

### ISSUE THREAD

**Issue by takielias** [rahulhaque/laravel-filepond#9]
If I use localhost as file storage, It works. On the other hand, I'm getting error when I use the moveTo() function in S3/wasabi storage.

![image](https://user-images.githubusercontent.com/38932580/146668434-221f190b-df33-43cd-85bd-37db44a135a5.png)

**Comment by rahulhaque** [comment]
@takielias did you update the disk configuration in `./config/filepond.php` before uploading?

**Comment by takielias** [comment]
> @takielias did you update the disk configuration in `./config/filepond.php` before uploading?

Yes

**Comment by rahulhaque** [comment]
@takielias I have not tested the package with any 3rd party storage providers or thought of supporting one when developing it. Now that I look into the code, I may come up with something to support 3rd party storage providers in near future.

Implying you can access the S3/wasabi instance from Laravel to perform read/write operations from your app, you can use the [API](https://github.com/rahulhaque/laravel-filepond#apis) implementation of the package to manually grab the file object and push it to S3/wasabi instance for now.

**Comment by rahulhaque** [comment]
@takielias here is the way to go. Get rid of any S3/wasabi configuration from `./config/filepond.php`. In your controller, after validating the file, use `getFile()` method to get the file object. There you will get access to Laravel's default `store()` method. Use it like `->getFile()->store('', 'wasabi')`. More on [here](https://laravel.com/docs/8.x/requests#storing-uploaded-files). Let me know of the attempt.

**Comment by takielias** [comment]
As I said before It works to upload wasabi but I'm getting errors when I use the moveTo().

**Comment by rahulhaque** [comment]
@takielias I believe wasabi is not your temporary storage, is it?

**Comment by takielias** [comment]
Yes, it is. Because It would consume more Bandwidth If I take a different temporary storage. I have fixed my issue using 
`        Storage::disk($filepond->disk)->move($filepond->filepath, $to);
`
And It works now. Thanks for your time & effort.

**Comment by MrMooky** [comment]
@takielias Would you be able to show your full solution? I'm currently trying to solve the same problem (I think). I would like to upload files directly to S3 and then just move them on S3 afterwards. Uploading them locally and then moving them to S3 takes too long for bigger files.

**Comment by takielias** [comment]
> @takielias Would you be able to show your full solution? I'm currently trying to solve the same problem (I think). I would like to upload files directly to S3 and then just move them on S3 afterwards. Uploading them locally and then moving them to S3 takes too long for bigger files.

@MrMooky 

For .env

```shell
FILESYSTEM_DRIVER=s3
FILEPOND_DISK=s3
```
And this is my function

```shell
function filePondDocumentUpload($file, $uploadPath)
{
    $filePond = Filepond::field($file);
    $path = $uploadPath . '/' . uniqid(time());
    $filePond->moveTo($path);
    $model = $filePond->getModel();
    $data['file_url'] = $path . "." . $model->extension;
    $data['basename'] = explode(".", $model->filename)[0];
    return $data;
}
```

**Comment by MrMooky** [comment]
@takielias Thanks. But moving bigger files with `moveTo()` still takes a long time though, even when using the same storage. Do you only upload smaller files?

**Comment by rahulhaque** [comment]
@MrMooky asking just to know as I don't have S3 access -
- Is it faster when you directly (using S3's interface) move large files in S3? 
- Is it faster if you move large files with laravel's `Storage` facade in S3?

**Comment by MrMooky** [comment]
@rahulhaque 

It is much faster when moving from folder to folder via sFTP, haven't tested directly in the S3 interface (not using AWS here). 

The `moveTo()` function provided by your package takes quite long with big files. It feels like they are being fetched fully before being moved.

But I ended up using `Storage::disk('attachments')->move($from, $to);` in a custom callback after the package is done uploading. Then moving 6 ~500MB files takes around 4s, which is good enough for my case.

**Comment by rahulhaque** [comment]
> The moveTo() function provided by your package takes quite long with big files. It feels like they are being fetched fully before being moved.

@MrMooky Yes. I have to consider if the moving/copying is happening between different storage as well.

> But I ended up using Storage::disk('attachments')->move($from, $to); in a custom callback after the package is done uploading. Then moving 6 ~500MB files takes around 4s, which is good enough for my case.

`Storage::move()` is faster when files are in same storage. 

I intended to suggest using this package's `getModel()` method to get the required info and laravel's `Storage` facade to move in such case. I think your solution can be implemented simply by checking if both storage is same.
